import "../../app/[locale]/globals.css";
export const metadata = {
  title: "koinfolio",
  description: "Generated by Next.js",
  icons: {
    icon: "/assets/favicons/favicon.ico",
  },
};
import Head from "next/head";
import Page from "./pageRenderer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/assets/favicons/favicon.ico" />
      </Head>
      <Page>
        <body>{children}</body>
      </Page>
    </html>
  );
}
