import "../../app/[locale]/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Page from "./pageRenderer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Page>
        <body>{children}</body>
      </Page>
    </html>
  );
}
