export const videos = [
  {
    title: "#001 Wieso ist das Hypethema «DEFI» so wichtig?",
    url: "https://www.youtube.com/embed/Bd1yxZF8-_k",
    thumbnail: "https://img.youtube.com/vi/Bd1yxZF8-_k/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#002 Lohnt es sich noch die alten OG Projekte zu halten oder lieber in die neuen investieren?",
    url: "https://www.youtube.com/embed/S0MXVx_utMA",
    thumbnail: "https://img.youtube.com/vi/S0MXVx_utMA/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#003 Denkst du es gibt noch einen Crash vor dem Halving?",
    url: "https://www.youtube.com/embed/vuFrXsQ69rU",
    thumbnail: "https://img.youtube.com/vi/vuFrXsQ69rU/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#004 Wie wahrscheinlich siehst du ein Bitcoin/Bullrun Top 2024?",
    url: "https://www.youtube.com/embed/d5s0pyBIMXE",
    thumbnail: "https://img.youtube.com/vi/d5s0pyBIMXE/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#005 Kann es überhaupt wieder eine so starke Altcoin Season geben, obwohl das ganze Kapital von den Institutionellen in die Bitcoin ETF’s fliesst?",
    url: "https://www.youtube.com/embed/KFJgvNotr9g",
    thumbnail: "https://img.youtube.com/vi/KFJgvNotr9g/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#006 Wie wichtig sind die Hypethemen im Bullrun und wieviele gibt es normalerweise in einem Zyklus?",
    url: "https://www.youtube.com/embed/GypsHkeEUHE",
    thumbnail: "https://img.youtube.com/vi/GypsHkeEUHE/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#007 Werden CBDC’s Projekte einen Hype im Bullrun erleben? Warum steigen diese Projekte nicht?",
    url: "https://www.youtube.com/embed/OUS2ePpp1Nk",
    thumbnail: "https://img.youtube.com/vi/OUS2ePpp1Nk/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#008 Wie kann man bei über 30 Projekten im Portfolio den Überblick behalten? Wie kann man die Überforderung überwinden?",
    url: "https://www.youtube.com/embed/5BZ3OJQmoKc",
    thumbnail: "https://img.youtube.com/vi/5BZ3OJQmoKc/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#009 Ab wann hört man auf Projekte zu akkumulieren um die Steuerfreiheit einzuhalten?",
    url: "https://www.youtube.com/embed/ITP57KG4PLk",
    thumbnail: "https://img.youtube.com/vi/ITP57KG4PLk/maxresdefault.jpg",
  },
  {
    title: "#010 Wann macht Bitcoin Sinn im Portfolio?",
    url: "https://www.youtube.com/embed/UlJiBNiBPek",
    thumbnail: "https://img.youtube.com/vi/UlJiBNiBPek/maxresdefault.jpg",
  },
  {
    title:
      "#011 Ist der Zug schon abgefahren? Auf einen Crash warten oder einkaufen?",
    url: "https://www.youtube.com/embed/R7Axl_jiJ8U",
    thumbnail: "https://img.youtube.com/vi/R7Axl_jiJ8U/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#012 Sollte man im Bullrun Altcoins verkaufen oder im Portfolio behalten?",
    url: "https://www.youtube.com/embed/DnAcFoQ209I",
    thumbnail: "https://img.youtube.com/vi/DnAcFoQ209I/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#013 Warum ist die Diversifizierung des Portfolios so wichtig?",
    url: "https://www.youtube.com/embed/kxYE5FnV6xU",
    thumbnail: "https://img.youtube.com/vi/kxYE5FnV6xU/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#014 Wann sollte man die Altcoins in einem Bullrun verkaufen?",
    url: "https://www.youtube.com/embed/4mnPj-vTz4U",
    thumbnail: "https://img.youtube.com/vi/4mnPj-vTz4U/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#015 Warum sind günstige Durchschnittspreise bei den Altcoins so wichtig?",
    url: "https://www.youtube.com/embed/II8kyJkHEcs",
    thumbnail: "https://img.youtube.com/vi/II8kyJkHEcs/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#016 Welche Hypethemen sind besonders wichtig im nächsten Bullrun?",
    url: "https://www.youtube.com/embed/Mto_QdZdciI",
    thumbnail: "https://img.youtube.com/vi/Mto_QdZdciI/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#017 Warum haben viele Altcoins einen besseren Mehrwert als Bitcoin?",
    url: "https://www.youtube.com/embed/llJGLRtwVhk",
    thumbnail: "https://img.youtube.com/vi/llJGLRtwVhk/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#018 Was ist bei einer Altcoinseason wichtig zu beachten?",
    url: "https://www.youtube.com/embed/BzCrYYCZCPE",
    thumbnail: "https://img.youtube.com/vi/BzCrYYCZCPE/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#019 Werden alle Altcoins wieder ihr ATH erreichen?",
    url: "https://www.youtube.com/embed/74DTBZOP-GU",
    thumbnail: "https://img.youtube.com/vi/74DTBZOP-GU/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#020 Wie wichtig ist es das Hypethema im Bullrun zu treffen?",
    url: "https://www.youtube.com/embed/2RHp5zHOSo8",
    thumbnail: "https://img.youtube.com/vi/2RHp5zHOSo8/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#021 Warum bist du überzeugt, dass dieser Bullrun der grösste Bullrun der Geschichte wird?",
    url: "https://www.youtube.com/embed/kSdlZ47F0Sk",
    thumbnail: "https://img.youtube.com/vi/kSdlZ47F0Sk/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#022 Was sollte man beachten um den Ausstieg bei den Altcoins nicht zu verpassen?",
    url: "https://www.youtube.com/embed/rpMAq2wnIkY",
    thumbnail: "https://img.youtube.com/vi/rpMAq2wnIkY/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#023 Wie bewältigt man Probleme mit Banküberweisungen während eines Bullruns?",
    url: "https://www.youtube.com/embed/zouGdHaViPg",
    thumbnail: "https://img.youtube.com/vi/zouGdHaViPg/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#024 Welche Gründe sprechen dagegen, in Börsentoken zu investieren?",
    url: "https://www.youtube.com/embed/cxg5nrvPHPI",
    thumbnail: "https://img.youtube.com/vi/cxg5nrvPHPI/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#025 Welche Fehler sollte man als Anfänger möglichst meiden?",
    url: "https://www.youtube.com/embed/eOnbY7IB2ZU",
    thumbnail: "https://img.youtube.com/vi/eOnbY7IB2ZU/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#026 Bitcoin: Es wird keine CRASHES mehr geben!?",
    url: "https://www.youtube.com/embed/lnsAqsAWAQE",
    thumbnail: "https://img.youtube.com/vi/lnsAqsAWAQE/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#027 Sollte man jetzt im Plus verkaufen oder auf die Altcoinseason warten?",
    url: "https://www.youtube.com/embed/5qOmAcHc4Kk",
    thumbnail: "https://img.youtube.com/vi/5qOmAcHc4Kk/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#028 Wird die Altcoin-Season durch die Bitcoin ETF’s ausgebremst werden?",
    url: "https://www.youtube.com/embed/svfr2suL8oI",
    thumbnail: "https://img.youtube.com/vi/svfr2suL8oI/maxresdefault.jpg",
  },
  {
    title: "#029 Sollte man in der Altcoin-Season seine Coins verkaufen?",
    url: "https://www.youtube.com/embed/C-91ZGgybvc",
    thumbnail: "https://img.youtube.com/vi/C-91ZGgybvc/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#031 Warum ist Bitcoin das neue Gold?",
    url: "https://www.youtube.com/embed/t_hWwCNrDbM",
    thumbnail: "https://img.youtube.com/vi/t_hWwCNrDbM/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#032 Wie sollte man vorgehen, wenn die neuen Coins ihre pessimistischen Preisziele niemals erreichen?",
    url: "https://www.youtube.com/embed/d130CFHkzkU",
    thumbnail: "https://img.youtube.com/vi/d130CFHkzkU/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#033 Auf welchen Indikator muss man besonders achten um den Beginn der Altcoin-Season zu erkennen?",
    url: "https://www.youtube.com/embed/3qZxWmVUo_Y",
    thumbnail: "https://img.youtube.com/vi/3qZxWmVUo_Y/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#034 Wie lange haben wir noch Zeit um zu investieren, bevor es zu spät ist?",
    url: "https://www.youtube.com/embed/gogIFT6lf-A",
    thumbnail: "https://img.youtube.com/vi/gogIFT6lf-A/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title:
      "#035 Welchen Effekt hat eine hohe Coininflation typischerweise auf den Preis des Coins?",
    url: "https://www.youtube.com/embed/80Hwzevc5h0",
    thumbnail: "https://img.youtube.com/vi/80Hwzevc5h0/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#036 Dieser neue Altcoin steigt!",
    url: "https://www.youtube.com/embed/X6JAKnF4Odw",
    thumbnail: "https://img.youtube.com/vi/X6JAKnF4Odw/maxresdefault.jpg",
    duration: "1:52",
  },

  {
    title: "#037 Altcoin Season: Das ist nicht normal!",
    url: "https://www.youtube.com/embed/2la9rfs3H60",
    thumbnail: "https://img.youtube.com/vi/2la9rfs3H60/maxresdefault.jpg",
    duration: "4:13",
  },
  {
    title: "#038 Wir haben nicht mehr viel Zeit!",
    url: "https://www.youtube.com/embed/gogIFT6lf-A",
    thumbnail: "https://img.youtube.com/vi/gogIFT6lf-A/maxresdefault.jpg",
    duration: "8:18",
  },

  {
    title: "#039 Ihr werdet es so stark bereuen!",
    url: "https://www.youtube.com/embed/raGNiQAg-6c",
    thumbnail: "https://img.youtube.com/vi/raGNiQAg-6c/maxresdefault.jpg",
    duration: "3:33",
  },
  {
    title: "#040 XRP, VET, CKB: Hört auf damit!",
    url: "https://www.youtube.com/embed/10NHgq-hcIA",
    thumbnail: "https://img.youtube.com/vi/10NHgq-hcIA/maxresdefault.jpg",
    duration: "2:15",
  },
  {
    title: "#041 Wenn das passiert, wird die ALT-SEASON GEWALTIG!",
    url: "https://www.youtube.com/embed/3qZxWmVUo_Y",
    thumbnail: "https://img.youtube.com/vi/3qZxWmVUo_Y/maxresdefault.jpg",
    duration: "4:00",
  },
  {
    title: "#042 Im BULLRUN mehrere ALT-SEASONS?",
    url: "https://www.youtube.com/embed/3wQcGCOm-iM",
    thumbnail: "https://img.youtube.com/vi/3wQcGCOm-iM/maxresdefault.jpg",
    duration: "3:11",
  },
  {
    title: "#043 Einstieg VERPASST? Es wird immer neue Chancen geben!",
    url: "https://www.youtube.com/embed/d130CFHkzkU",
    thumbnail: "https://img.youtube.com/vi/d130CFHkzkU/maxresdefault.jpg",
    duration: "3:18",
  },
  {
    title: "#044 In der ALT-SEASON alles VERKAUFEN?",
    url: "https://www.youtube.com/embed/C-91ZGgybvc",
    thumbnail: "https://img.youtube.com/vi/C-91ZGgybvc/maxresdefault.jpg",
    duration: "4:33",
  },
  {
    title: "#045 Du musst den KRYPTO MARKT verstehen!",
    url: "https://www.youtube.com/embed/lIjvoyTqH7c",
    thumbnail: "https://img.youtube.com/vi/lIjvoyTqH7c/maxresdefault.jpg",
    duration: "5:49",
  },
  {
    title: "#046 BITCOIN ist das NEUE GOLD!",
    url: "https://www.youtube.com/embed/leKe5ayk3qI",
    thumbnail: "https://img.youtube.com/vi/leKe5ayk3qI/maxresdefault.jpg",
    duration: "3:19",
  },
  {
    title: "#047 ALT-SEASON wird durch BTC-ETF stark GEBREMST!",
    url: "https://www.youtube.com/embed/svfr2suL8oI",
    thumbnail: "https://img.youtube.com/vi/svfr2suL8oI/maxresdefault.jpg",
    duration: "2:32",
  },
  {
    title: "#048 Krypto-Portfolio: Darauf lege ich wert!",
    url: "https://www.youtube.com/embed/t_hWwCNrDbM",
    thumbnail: "https://img.youtube.com/vi/t_hWwCNrDbM/maxresdefault.jpg",
    duration: "3:09",
  },
  {
    title: "#049 VTHO statt VET!?",
    url: "https://www.youtube.com/embed/2cqHBEldO28",
    thumbnail: "https://img.youtube.com/vi/2cqHBEldO28/maxresdefault.jpg",
    duration: "3:59",
  },
  {
    title: "#050 Dieser Top Altcoin ist überbewertet!",
    url: "https://www.youtube.com/embed/zz-l7PDL7LI",
    thumbnail: "https://img.youtube.com/vi/zz-l7PDL7LI/maxresdefault.jpg",
    duration: "1:16",
  },
  {
    title: "#051 Diese ALTCOINS sind FEHL AM PLATZ!",
    url: "https://www.youtube.com/embed/sup0JVWBbM8",
    thumbnail: "https://img.youtube.com/vi/sup0JVWBbM8/maxresdefault.jpg",
    duration: "5:30",
  },
  {
    title: "#052 Bitcoin: Das musst du verstehen!",
    url: "https://www.youtube.com/embed/xJaYcedg60s",
    thumbnail: "https://img.youtube.com/vi/xJaYcedg60s/maxresdefault.jpg",
    duration: "3:57",
  },
  {
    title: "#053 MATIC, FET, FTM: 10$ Möglich?",
    url: "https://www.youtube.com/embed/fQkhp2-kC14",
    thumbnail: "https://img.youtube.com/vi/fQkhp2-kC14/maxresdefault.jpg",
    duration: "7:00",
  },
  {
    title: "#054 Diese Altcoins werde ich immer meiden!",
    url: "https://www.youtube.com/embed/xrx8GPFGl4A",
    thumbnail: "https://img.youtube.com/vi/xrx8GPFGl4A/maxresdefault.jpg",
    duration: "1:24",
  },
  {
    title: "#055 ALGO: Starkes Potenzial!",
    url: "https://www.youtube.com/embed/4C0lqsSc0zQ",
    thumbnail: "https://img.youtube.com/vi/4C0lqsSc0zQ/maxresdefault.jpg",
    duration: "2:49",
  },
  {
    title: "#056 Ich habe im Bullrun starke Fehler gemacht!",
    url: "https://www.youtube.com/embed/tJfXJ3Zg7qI",
    thumbnail: "https://img.youtube.com/vi/tJfXJ3Zg7qI/maxresdefault.jpg",
    duration: "2:29",
  },
  {
    title: "#057 Sehr viele ALTCOINS werden STERBEN!",
    url: "https://www.youtube.com/embed/c4ZMj7ubj2Q",
    thumbnail: "https://img.youtube.com/vi/c4ZMj7ubj2Q/maxresdefault.jpg",
    duration: "4:13",
  },
  {
    title: "#058 VET: Kritik! RNDR: Explosion? SOL: Hochstufen!",
    url: "https://www.youtube.com/embed/oka3oe-ZUqg",
    thumbnail: "https://img.youtube.com/vi/oka3oe-ZUqg/maxresdefault.jpg",
    duration: "2:10",
  },
  {
    title: "#059 Dieser FEHLER tut mir richtig weh!",
    url: "https://www.youtube.com/embed/RO3T8FDmggU",
    thumbnail: "https://img.youtube.com/vi/RO3T8FDmggU/maxresdefault.jpg",
    duration: "3:04",
  },
  {
    title: "#060 Wir brauchen KORREKTUREN im BULLRUN!",
    url: "https://www.youtube.com/embed/ypEzYgAPLQ8",
    thumbnail: "https://img.youtube.com/vi/ypEzYgAPLQ8/maxresdefault.jpg",
    duration: "2:37",
  },
  {
    title: "#061 Was muss passieren, damit ALTCOIN SEASON beginnt?",
    url: "https://www.youtube.com/embed/sFO0eUul-P8",
    thumbnail: "https://img.youtube.com/vi/sFO0eUul-P8/maxresdefault.jpg",
    duration: "1:29",
  },
  {
    title: "#062 So erkennst du TOTE ALTCOINS!",
    url: "https://www.youtube.com/embed/y9m7TErPmx4",
    thumbnail: "https://img.youtube.com/vi/y9m7TErPmx4/maxresdefault.jpg",
    duration: "2:10",
  },
  {
    title: "Ist der KI-HYPE jetzt VORBEI?",
    url: "https://www.youtube.com/embed/GhJEM5YVGBw",
    thumbnail: "https://img.youtube.com/vi/GhJEM5YVGBw/maxresdefault.jpg",
    duration: "7:38",
  },
  {
    title: "#063 ALT-SEASON: Welches Hypethema?",
    url: "https://www.youtube.com/embed/fDaamX3fsLQ",
    thumbnail: "https://img.youtube.com/vi/fDaamX3fsLQ/maxresdefault.jpg",
    duration: "2:33",
  },
  {
    title: "#064 Neue KRYPTOS direkt KAUFEN!?",
    url: "https://www.youtube.com/embed/rYWnXeUbqJo",
    thumbnail: "https://img.youtube.com/vi/rYWnXeUbqJo/maxresdefault.jpg",
    duration: "4:08",
  },
  {
    title: "#064 Dieses ALTCOIN-THEMA wird es schwer haben!",
    url: "https://www.youtube.com/embed/1qY7M2AivnM",
    thumbnail: "https://img.youtube.com/vi/1qY7M2AivnM/maxresdefault.jpg",
    duration: "3:50",
  },
  {
    title: "#065 ALT-SEASON: Wann und wie oft?",
    url: "https://www.youtube.com/embed/QhvEnprZeww",
    thumbnail: "https://img.youtube.com/vi/QhvEnprZeww/maxresdefault.jpg",
    duration: "2:07",
  },
  {
    title: "#066 ALL-IN in KI-Kryptos?",
    url: "https://www.youtube.com/embed/F6EA29gjsVM",
    thumbnail: "https://img.youtube.com/vi/F6EA29gjsVM/maxresdefault.jpg",
    duration: "2:10",
  },
  {
    title: "#067 Diese 4 Small Caps gefallen mir gut!",
    url: "https://www.youtube.com/embed/TMilhGepuk8",
    thumbnail: "https://img.youtube.com/vi/TMilhGepuk8/maxresdefault.jpg",
    duration: "1:55",
  },
  {
    title: "#068 Mein besonderes Learning im Kryptomarkt!",
    url: "https://www.youtube.com/embed/D58JfGW6e60",
    thumbnail: "https://img.youtube.com/vi/D58JfGW6e60/maxresdefault.jpg",
    duration: "6:47",
  },
  {
    title: "#069 KI-KRYPTOS: Das Dilemma!",
    url: "https://www.youtube.com/embed/3PCfgyuTU68",
    thumbnail: "https://img.youtube.com/vi/3PCfgyuTU68/maxresdefault.jpg",
    duration: "3:56",
  },
  {
    title: "#070 VET & VTHO: Was ein STARKES Potenzial! 🤯",
    url: "https://www.youtube.com/embed/6xkbd6ajOZc",
    thumbnail: "https://img.youtube.com/vi/6xkbd6ajOZc/maxresdefault.jpg",
    duration: "4:50",
  },
  {
    title: "#071 Diese ALTCOINS sind JETZT GÜNSTIG!",
    url: "https://www.youtube.com/embed/MelLFNqdN2s",
    thumbnail: "https://img.youtube.com/vi/MelLFNqdN2s/maxresdefault.jpg",
    duration: "12:14",
  },
  {
    title: "#072 Vorsicht bei NEUEN ALTCOINS!",
    url: "https://www.youtube.com/embed/udZ8TesH9Hk",
    thumbnail: "https://img.youtube.com/vi/udZ8TesH9Hk/maxresdefault.jpg",
    duration: "2:49",
  },
  {
    title: "#073 Jetzt noch KAUFEN oder WARTEN!?",
    url: "https://www.youtube.com/embed/9vrSr_S-jEA",
    thumbnail: "https://img.youtube.com/vi/9vrSr_S-jEA/maxresdefault.jpg",
    duration: "2:40",
  },
  {
    title: "#074 Hört auf damit!",
    url: "https://www.youtube.com/embed/oV7ewYtIAJ0",
    thumbnail: "https://img.youtube.com/vi/oV7ewYtIAJ0/maxresdefault.jpg",
    duration: "2:14",
  },
  {
    title: "#075 Die größte ALTCOIN-SEASON der Geschichte!?",
    url: "https://www.youtube.com/embed/jRF73jG3fXI",
    thumbnail: "https://img.youtube.com/vi/jRF73jG3fXI/maxresdefault.jpg",
    duration: "3:47",
  },
  {
    title: "#076 Das darf dir NICHT passieren!",
    url: "https://www.youtube.com/embed/qjwdjWW5Pfc",
    thumbnail: "https://img.youtube.com/vi/qjwdjWW5Pfc/maxresdefault.jpg",
    duration: "3:45",
  },
  {
    title: "#077 QUANT wird uns ALLE stark ÜBERRASCHEN!",
    url: "https://www.youtube.com/embed/k9R1x0JR-BY",
    thumbnail: "https://img.youtube.com/vi/k9R1x0JR-BY/maxresdefault.jpg",
    duration: "4:07",
  },
  {
    title: "#078 Mache NICHT diesen FEHLER!",
    url: "https://www.youtube.com/embed/aQavDKKV7Ck",
    thumbnail: "https://img.youtube.com/vi/aQavDKKV7Ck/maxresdefault.jpg",
    duration: "3:57",
  },
  {
    title: "#079 10x ab heute möglich? + ALGO, DOT, AZERO",
    url: "https://www.youtube.com/embed/tXWfMBU2FP0",
    thumbnail: "https://img.youtube.com/vi/tXWfMBU2FP0/maxresdefault.jpg",
    duration: "1:36",
  },
  {
    title: "#080 Diese ALTCOINS sind ERFRISCHEND!",
    url: "https://www.youtube.com/embed/697edmDSSaU",
    thumbnail: "https://img.youtube.com/vi/697edmDSSaU/maxresdefault.jpg",
    duration: "4:08",
  },
  {
    title: "#081 Ich freue mich auf den Bullrun!",
    url: "https://www.youtube.com/embed/pHZRwgwA0jw",
    thumbnail: "https://img.youtube.com/vi/pHZRwgwA0jw/maxresdefault.jpg",
    duration: "2:03",
  },
  {
    title: "#082 Wir können NICHT alle gewinnen!",
    url: "https://www.youtube.com/embed/bNJLeEM0FoU",
    thumbnail: "https://img.youtube.com/vi/bNJLeEM0FoU/maxresdefault.jpg",
    duration: "1:32",
  },
  {
    title: "#083 GALA & SOLANA: Chancen rechtzeitig nutzen!",
    url: "https://www.youtube.com/embed/gCEF7WMAcQ8",
    thumbnail: "https://img.youtube.com/vi/gCEF7WMAcQ8/maxresdefault.jpg",
    duration: "2:07",
  },
  {
    title: "#084 So kannst du nur gewinnen!",
    url: "https://www.youtube.com/embed/fVFr73XLHe8",
    thumbnail: "https://img.youtube.com/vi/fVFr73XLHe8/maxresdefault.jpg",
    duration: "1:31",
  },
  {
    title: "#085 So ZERSTÖRST du dein PORTFOLIO!",
    url: "https://www.youtube.com/embed/gTqCQj39bx4",
    thumbnail: "https://img.youtube.com/vi/gTqCQj39bx4/maxresdefault.jpg",
    duration: "2:43",
  },
  {
    title: "#086 Wie UNTERBEWERTETE Altcoins erkennen?",
    url: "https://www.youtube.com/embed/_ccnNgZn78I",
    thumbnail: "https://img.youtube.com/vi/_ccnNgZn78I/maxresdefault.jpg",
    duration: "1:41",
  },
  {
    title: "#087 Eines der besten KI Kryptos!",
    url: "https://www.youtube.com/embed/QerkeywL2Tk",
    thumbnail: "https://img.youtube.com/vi/QerkeywL2Tk/maxresdefault.jpg",
    duration: "5:32",
  },
  {
    title: "#088 Bis wann noch EINKAUFEN?",
    url: "https://www.youtube.com/embed/nrwKeJhZyyg",
    thumbnail: "https://img.youtube.com/vi/nrwKeJhZyyg/maxresdefault.jpg",
    duration: "6:11",
  },
  {
    title: "#089 Diese Krypto wird jeden Tag besser!",
    url: "https://www.youtube.com/embed/bONKMVlccEU",
    thumbnail: "https://img.youtube.com/vi/bONKMVlccEU/maxresdefault.jpg",
    duration: "2:26",
  },
  {
    title: "#090 Dieser neue Altcoin gefällt mir sehr!",
    url: "https://www.youtube.com/embed/qa6-JDsuuPg",
    thumbnail: "https://img.youtube.com/vi/qa6-JDsuuPg/maxresdefault.jpg",
    duration: "2:16",
  },
  {
    title: "#091 Das ZERSTÖRT dein Portfolio!",
    url: "https://www.youtube.com/embed/R0drf52oBa4",
    thumbnail: "https://img.youtube.com/vi/R0drf52oBa4/maxresdefault.jpg",
    duration: "5:38",
  },
  {
    title: "#092 Altcoins haben ihr TOP schon gesehen!?",
    url: "https://www.youtube.com/embed/SPXHM76eG8M",
    thumbnail: "https://img.youtube.com/vi/SPXHM76eG8M/maxresdefault.jpg",
    duration: "2:06",
  },
  {
    title: "#093 ALTCOINS sind eine MACHT!",
    url: "https://www.youtube.com/embed/qhu2zJgP7CI",
    thumbnail: "https://img.youtube.com/vi/qhu2zJgP7CI/maxresdefault.jpg",
    duration: "3:49",
  },
  {
    title: "#094 Ab heute ein 20x noch möglich?",
    url: "https://www.youtube.com/embed/w6l3SBLiJpg",
    thumbnail: "https://img.youtube.com/vi/w6l3SBLiJpg/maxresdefault.jpg",
    duration: "2:48",
  },
  {
    title: "#095 Der SCHLECHTESTE ALTCOIN ist...",
    url: "https://www.youtube.com/embed/XgSXQTOXrTs",
    thumbnail: "https://img.youtube.com/vi/XgSXQTOXrTs/maxresdefault.jpg",
    duration: "2:39",
  },
  {
    title: "#096 Altcoin Season noch 2024!?",
    url: "https://www.youtube.com/embed/szicJBqE2Ec",
    thumbnail: "https://img.youtube.com/vi/szicJBqE2Ec/maxresdefault.jpg",
    duration: "2:21",
  },
  {
    title: "#097 Von diesen Altcoins halte ich Abstand!",
    url: "https://www.youtube.com/embed/TshSH0-seAA",
    thumbnail: "https://img.youtube.com/vi/TshSH0-seAA/maxresdefault.jpg",
    duration: "3:13",
  },
  {
    title: "#098 ALTCOIN-Season: Darauf musst du achten!",
    url: "https://www.youtube.com/embed/TVs1SAXDSS8",
    thumbnail: "https://img.youtube.com/vi/TVs1SAXDSS8/maxresdefault.jpg",
    duration: "3:07",
  },
  {
    title: "#099 Dieser ALTCOIN ist UNTERBEWERTET!",
    url: "https://www.youtube.com/embed/SCAe6Hu5EjE",
    thumbnail: "https://img.youtube.com/vi/SCAe6Hu5EjE/maxresdefault.jpg",
    duration: "2:02",
  },
  {
    title: "#100 Krypto HODL ist komplett bescheuert! - Reaktion",
    url: "https://www.youtube.com/embed/coPLnXEt6V0",
    thumbnail: "https://img.youtube.com/vi/coPLnXEt6V0/maxresdefault.jpg",
    duration: "4:25",
  },
  {
    title: "#101 Wann kommt endlich die Altcoin Explosion?",
    url: "https://www.youtube.com/embed/Q0VJkca-cNI",
    thumbnail: "https://img.youtube.com/vi/Q0VJkca-cNI/maxresdefault.jpg",
    duration: "4:53",
  },
  {
    title: "#102 Dieser ALTCOIN Hype wird GEWALTIG!",
    url: "https://www.youtube.com/embed/BQqvmvAdAJk",
    thumbnail: "https://img.youtube.com/vi/BQqvmvAdAJk/maxresdefault.jpg",
    duration: "4:53",
  },
  {
    title: "#103 Deine GIER wird dich ZERSTÖREN!",
    url: "https://www.youtube.com/embed/jX8RmC_HaEE",
    thumbnail: "https://img.youtube.com/vi/jX8RmC_HaEE/maxresdefault.jpg",
    duration: "2:20",
  },
  {
    title: "#104 Dieser ALTCOIN HYPE wird die KI Kryptos stark treffen!",
    url: "https://www.youtube.com/embed/6KUQuntShsY",
    thumbnail: "https://img.youtube.com/vi/6KUQuntShsY/maxresdefault.jpg",
    duration: "4:24",
  },
  {
    title: "#105 Dieser ALTCOIN wird viele überraschen!",
    url: "https://www.youtube.com/embed/T0Eym-Ci_t4",
    thumbnail: "https://img.youtube.com/vi/T0Eym-Ci_t4/maxresdefault.jpg",
    duration: "4:02",
  },
  {
    title: "#106 Mein neues Projekt!",
    url: "https://www.youtube.com/embed/V_GuMgLTgek",
    thumbnail: "https://img.youtube.com/vi/V_GuMgLTgek/maxresdefault.jpg",
    duration: "4:05",
  },
  {
    title: "#107 ETH-ETF wird die ALTCOIN-SEASON stärker machen!",
    url: "https://www.youtube.com/embed/G_69rWuIEyc",
    thumbnail: "https://img.youtube.com/vi/G_69rWuIEyc/maxresdefault.jpg",
    duration: "3:06",
  },
  {
    title: "#108 Der kommende Bullrun wird gigantisch!",
    url: "https://www.youtube.com/embed/hK19h9hfkrE",
    thumbnail: "https://img.youtube.com/vi/hK19h9hfkrE/maxresdefault.jpg",
    duration: "5:08",
  },
  {
    title: "#109 Bitcoin EXPLOSION, dann folgen die ALTCOINS!",
    url: "https://www.youtube.com/embed/8Ntr35dnjGU",
    thumbnail: "https://img.youtube.com/vi/8Ntr35dnjGU/maxresdefault.jpg",
    duration: "2:07",
  },
  {
    title: "#110 Welche Altcoins sind noch günstig?",
    url: "https://www.youtube.com/embed/kmDl-E5dJOA",
    thumbnail: "https://img.youtube.com/vi/kmDl-E5dJOA/maxresdefault.jpg",
    duration: "2:07",
  },
  {
    title: "#111 Er hat 109 Altcoins im Portfolio!",
    url: "https://www.youtube.com/embed/jSputrskVSA",
    thumbnail: "https://img.youtube.com/vi/jSputrskVSA/maxresdefault.jpg",
    duration: "2:41",
  },
  {
    title: "#112 ALTCOINS die im Bärenmarkt NICHT steigen... 🤯",
    url: "https://www.youtube.com/embed/EOp9um2V9CY",
    thumbnail: "https://img.youtube.com/vi/EOp9um2V9CY/maxresdefault.jpg",
    duration: "4:14",
  },
  {
    title: "#113 Künstliche Intiligenz wird alles übernehmen!",
    url: "https://www.youtube.com/embed/VPA34eRHK9U",
    thumbnail: "https://img.youtube.com/vi/VPA34eRHK9U/maxresdefault.jpg",
    duration: "2:12",
  },
  {
    title: "#114 Kann der BULLRUN abgebrochen werden?",
    url: "https://www.youtube.com/embed/yT348jKmpe8",
    thumbnail: "https://img.youtube.com/vi/yT348jKmpe8/maxresdefault.jpg",
    duration: "3:56",
  },
  {
    title: "#115 Diese GAMING KRYPTO ist ÜBERRAGEND!",
    url: "https://www.youtube.com/embed/xQ_4Ur3Syeo",
    thumbnail: "https://img.youtube.com/vi/xQ_4Ur3Syeo/maxresdefault.jpg",
    duration: "2:03",
  },
  {
    title: "#116 Kann dieser Altcoin von heute 100x machen?",
    url: "https://www.youtube.com/embed/w5n6d9T5FHA",
    thumbnail: "https://img.youtube.com/vi/w5n6d9T5FHA/maxresdefault.jpg",
    duration: "3:01",
  },
  {
    title: "#117 SO wirst du viel Geld verlieren!",
    url: "https://www.youtube.com/embed/FU6G8_GLz9g",
    thumbnail: "https://img.youtube.com/vi/FU6G8_GLz9g/maxresdefault.jpg",
    duration: "2:21",
  },
  {
    title: "#118 Diese TOP-ALTCOINS sind SOLANA-KILLER!?",
    url: "https://www.youtube.com/embed/ignCymEVrU8",
    thumbnail: "https://img.youtube.com/vi/ignCymEVrU8/maxresdefault.jpg",
    duration: "3:39",
  },
  {
    title: "#119 Altcoin Season: Aufpassen!",
    url: "https://www.youtube.com/embed/0TRUBtveTBs",
    thumbnail: "https://img.youtube.com/vi/0TRUBtveTBs/maxresdefault.jpg",
    duration: "2:34",
  },
  {
    title: "#120 AI Kryptos: Vorsicht, der Hype vergeht schnell!",
    url: "https://www.youtube.com/embed/hbd2C9gRfTA",
    thumbnail: "https://img.youtube.com/vi/hbd2C9gRfTA/maxresdefault.jpg",
    duration: "4:01",
  },
  {
    title: "#121 Krypto: Geiz ist Geil!",
    url: "https://www.youtube.com/embed/vDnSNS2rMq0",
    thumbnail: "https://img.youtube.com/vi/vDnSNS2rMq0/maxresdefault.jpg",
    duration: "1:27",
  },
  {
    title: "#122 Warum nicht so handeln wie die Wale?",
    url: "https://www.youtube.com/embed/HHrF_KZh6f8",
    thumbnail: "https://img.youtube.com/vi/HHrF_KZh6f8/maxresdefault.jpg",
    duration: "4:14",
  },
  {
    title: "#123 Altcoins werden immer STÄRKER!",
    url: "https://www.youtube.com/embed/vbMNjyCAlgI",
    thumbnail: "https://img.youtube.com/vi/vbMNjyCAlgI/maxresdefault.jpg",
    duration: "2:24",
  },
  {
    title: "#124 Warum fallen Altcoins, wenn Bitcoin fällt?",
    url: "https://www.youtube.com/embed/uFqZBb03HRQ",
    thumbnail: "https://img.youtube.com/vi/uFqZBb03HRQ/maxresdefault.jpg",
    duration: "3:09",
  },
  {
    title: "#125 Der nächste Bullrun wird nicht so stark!",
    url: "https://www.youtube.com/embed/tq2c9U3-Irs",
    thumbnail: "https://img.youtube.com/vi/tq2c9U3-Irs/maxresdefault.jpg",
    duration: "3:12",
  },
  {
    title: "#126 Krypto wird leben verändern!!!",
    url: "https://www.youtube.com/embed/O8IoHlanJg4",
    thumbnail: "https://img.youtube.com/vi/O8IoHlanJg4/maxresdefault.jpg",
    duration: "3:23",
  },
  {
    title: "#127 Bitcoin FÄLLT! Das ist jetzt wicjtig!",
    url: "https://www.youtube.com/embed/ik6hOgXyQ64",
    thumbnail: "https://img.youtube.com/vi/ik6hOgXyQ64/maxresdefault.jpg",
    duration: "3:37",
  },
  {
    title: "#128 Wie weit kann NEAR noch CRASHEN!?",
    url: "https://www.youtube.com/embed/iptO0-hsa0A",
    thumbnail: "https://img.youtube.com/vi/iptO0-hsa0A/maxresdefault.jpg",
    duration: "3:04",
  },
  {
    title: "#129 Bitcoin: Im Juli folgt die Explosion?",
    url: "https://www.youtube.com/embed/r7nzDIUwIo0",
    thumbnail: "https://img.youtube.com/vi/r7nzDIUwIo0/maxresdefault.jpg",
    duration: "1:37",
  },
  {
    title: "#130 Diese TOP ALTCOINS fallen WENIGER!",
    url: "https://www.youtube.com/embed/fm-9mIY_LQ4",
    thumbnail: "https://img.youtube.com/vi/fm-9mIY_LQ4/maxresdefault.jpg",
    duration: "5:32",
  },
];
